name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up the JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version-file: .java-version
      - name: Build
        run: mvn --batch-mode install
